# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            kanublog
url:              http://kanud.github.io/kanublog
baseurl:          http://kanud.github.io/kanublog/
paginate:         5

# Custom vars
version:             0.0.1
github:
  repo:              https://github.com/kanud/kanublog

gems:
- jekyll-gist
- jekyll-paginate
