# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            kanu’s blog
tagline:          ‘hacks and bets’
url:              http://kanud.github.io
baseurl:          http://kanud.github.io/kanublog/

author:
  name:           ‘Chinmay Deshpande’
  url:            https://twitter.com/KanuDeshpande

paginate:         5

# Custom vars
version:             0.0.1
github:
  repo:              https://github.com/kanud/kanublog

gems:
- jekyll-gist
- jekyll-paginate
