# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            kanu’s blog
tagline:          ‘hacks and bets’
description:      '<a href="https://twitter.com/KanuDeshpande” target="_blank”>@KanuDeshpande</a>.'
url:              http://kanud.github.io/kanublog/
baseurl:          “http://kanud.github.io/kanublog/”

author:
  name:           ‘Chinmay Deshpande’
  url:            https://twitter.com/KanuDeshpande

paginate:         5

gems:
- jekyll-gist
- jekyll-paginate
