# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            kanublog
tagline:          hacks and bets
url:              http://kanud.github.io
baseurl:          http://kanud.github.io/
paginate:         1

# Custom vars
version:             0.0.1
github:
  repo:              https://github.com/kanud/kanud.github.io

gems:
- jekyll-gist
- jekyll-paginate
