---
layout: post
title: The Surest Way to Become Old
---
I've heard one guy too many complaining about inflation. Booo the increase in the mess bill <em >:sob:</em> (a measly <img src="http://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Indian_Rupee_symbol.svg/7px-Indian_Rupee_symbol.svg.png" alt="INR" ></img>5, I think), waaah the tuition fee hike <em >:sigh:
</em>The guy then goes on to give a brilliant explanation about why the fee hike isn't justified and now I'm tired of arguing back and being thought of (probably) as an idiot. So let me break it down for you:
<ul >
	<li >You don't have a problem with the mess bill. You have a problem with everything humans have done so far and everything that's in the place we call the "World". And I feel terrible to break this to you, but:</li>
	<li >You remember that?<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Indian_Rupee_symbol.svg/7px-Indian_Rupee_symbol.svg.png" alt="INR" ></img>100 note you had last year? Well, that's actually worth less that?<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Indian_Rupee_symbol.svg/7px-Indian_Rupee_symbol.svg.png" alt="INR" ></img>92 now, estimating conservatively. It depends on what you want to buy with that note. It could even be worth less than?<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Indian_Rupee_symbol.svg/7px-Indian_Rupee_symbol.svg.png" alt="INR" ></img>58.</li>
</ul>
<div >So before you go on a mindless rant, read a beginner-level book on economics. <em >Any </em>book.
Or maybe just get something off the net, like this:?<a href="http://makanaka.wordpress.com/2011/01/02/food-inflation-crippled-indias-households-in-2010/" >http://makanaka.wordpress.com/2011/01/02/food-inflation-crippled-indias-households-in-2010/</a></div>
<div >You could even go to the market and jot down the prices of stuff, come back a year later and compare. I'll bet you?<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Indian_Rupee_symbol.svg/7px-Indian_Rupee_symbol.svg.png" alt="INR" ></img>100, no,?<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Indian_Rupee_symbol.svg/7px-Indian_Rupee_symbol.svg.png" alt="INR" ></img>110 that on an average prices have increased by more than?<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Indian_Rupee_symbol.svg/7px-Indian_Rupee_symbol.svg.png" alt="INR" ></img>5.</div>
<div >"OK <em >Kanu :smirk: </em>, but the mess food is so bad that the hike obviously justified :pwned:," to which I retort, inflation doesn't mean an increase in the quality of the good. That's how the world works, I'm terribly sorry, take it up with God if you want to, but it's going to cost you more than last year to get the <em >exact same sucky food</em>.
So please stop whining. You are all smart people and I hate to imagine you telling your kids, "<em >Hamare zamane main Eclairs sirf?<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Indian_Rupee_symbol.svg/7px-Indian_Rupee_symbol.svg.png" alt="INR" ></img>1 ka hota tha." </em>Bottom line:<em >
</em><strong >If you don't want to become an inflation-buddha, please understand the concept of inflation.?</strong></div>
<div >There is no free lunch.</div>